### ISSUE TITLE
The sentences chosen to form the summary are concatenated without white spaces.

### ISSUE THREAD

**Issue by GirayEryilmaz** [teaddict/turkce-metin-ozetleme-scala#1]
Returned summary is concatenation of chosen sentences but they are concatenated without white spaces in between. 

I believe changing `.mkSting`'s to `.mkString(" ")` 's in `/src/main/scala/com/summarizer/services/SummaryService.scala` may resolve the issue.

**Comment by teaddict** [comment]
Thanks, didn't notice that. I changed it to `.mkString(" ")`
